import "dotenv/config"; // load SESSION_SECRET so the dev cookie check matches the backend
import type { Connect, Plugin } from "vite";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { readFile } from "node:fs/promises";
import { PUBLIC_PATHS } from "./website/routes";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "vite";
import solid from "vite-plugin-solid";
import { readSession, SESSION_COOKIE } from "./services/utils/auth";

const abs = (p: string): string => fileURLToPath(new URL(p, import.meta.url));

// Stamped onto every analytics event, so a regression can be bounded to a deploy. Render injects
// the sha; locally git has it; a tarball build with neither says so rather than guessing.
function appBuild(): string {
    const injected = process.env.RENDER_GIT_COMMIT?.trim();
    if (injected) return injected.slice(0, 7);
    try {
        return execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim();
    } catch {
        return "unknown";
    }
}

function cookieValue(header: string | undefined, name: string): string | undefined {
    for (const part of header?.split(";") ?? []) {
        const eq = part.indexOf("=");
        if (eq > 0 && part.slice(0, eq).trim() === name) return part.slice(eq + 1).trim();
    }
    return undefined;
}

// Must mirror the routing in services/server.ts, else localhost and prod disagree on "/".
function appSpaFallback(): Plugin {
    const handler =
        (preview: boolean): Connect.NextHandleFunction =>
        async (req, res, next) => {
            const url = new URL(req.url ?? "/", "http://localhost");
            const path = url.pathname;
            if (/^\/(?:api|mcp|oauth|\.well-known|assets|fonts)(?:\/|$)/.test(path)) return next();
            if (path === "/robots.txt" || path === "/sitemap.xml") {
                if (!preview) {
                    res.setHeader("Content-Type", "text/plain");
                    res.statusCode = 404;
                    res.end("Crawler files are generated by pnpm build");
                    return;
                }
                try {
                    res.setHeader(
                        "Content-Type",
                        path.endsWith(".xml") ? "application/xml" : "text/plain",
                    );
                    res.end(await readFile(`./dist${path}`, "utf8"));
                } catch (error) {
                    next(error);
                }
                return;
            }
            if (!(req.headers.accept ?? "").includes("text/html")) return next();
            const authed = readSession(cookieValue(req.headers.cookie, SESSION_COOKIE)) !== null;
            const clean = path.length > 1 ? path.replace(/\/$/, "") : path;
            res.setHeader("Cache-Control", "private, no-cache");
            const redirect = (location: string): void => {
                res.statusCode = 301;
                res.setHeader("Location", location);
                res.end();
            };
            if (clean === "/home" && !authed) return redirect("/");
            if (clean === "/pricing" && !authed && !url.search) return redirect("/#pricing");
            if (clean !== path && PUBLIC_PATHS.includes(clean))
                return redirect(`${clean}${url.search}`);
            if (PUBLIC_PATHS.includes(clean) || clean === "/home") {
                if (clean === "/" && authed) req.url = "/app/index.html";
                else if (preview) {
                    const name =
                        clean === "/" || clean === "/home"
                            ? "home"
                            : clean.slice(1).replaceAll("/", "-");
                    req.url = `/marketing/${name}.html`;
                } else req.url = "/index.html";
            } else if (path.startsWith("/p/")) req.url = "/publish/index.html";
            else if (
                /^\/(?:app|login|signup|connect|welcome|templates|shared|trash|pricing(?:\/activity)?|settings(?:\/[^/]+){0,2}|account(?:\/[^/]+)?|(?:folder|invite|collab|edit|present)\/[^/]+)\/?$/.test(
                    path,
                )
            )
                req.url = "/app/index.html";
            else if (!/\.\w+$/.test(path)) {
                res.statusCode = 404;
                res.end("Page not found");
                return;
            }
            if (req.url === "/app/index.html") res.setHeader("X-Robots-Tag", "noindex");
            next();
        };

    return {
        name: "app-spa-fallback",
        configureServer(server) {
            server.middlewares.use(handler(false));
        },
        // preview serves dist/ the way the Hono server does in production, routes included
        configurePreviewServer(server) {
            server.middlewares.use(handler(true));
        },
    };
}

export default defineConfig({
    root: ".",
    define: { "import.meta.env.VITE_APP_BUILD": JSON.stringify(appBuild()) },
    publicDir: "public", // vendored fonts and stable marketing identity assets
    server: {
        port: 8600,
        strictPort: true,
        // A tunnelled dev server is how an external MCP client (Claude, ChatGPT) reaches this
        // machine, and Vite refuses an unknown Host by default. Named suffixes rather than `true`,
        // so this stays a hole only the tunnels we actually use can come through.
        allowedHosts: [".trycloudflare.com", ".ngrok-free.app", ".ngrok.io", ".loca.lt"],
        // Regex key, not "/api": a bare prefix would also swallow the /api.ts module request.
        proxy: {
            "^/api/": {
                target: "http://localhost:8601",
                changeOrigin: true,
                ws: true, // the collaboration socket upgrades on /api/artifacts/:id/collab
            },
            // root-mounted in prod because their paths are fixed by spec, so dev proxies them too
            // rather than letting the SPA fallback answer an MCP client with HTML
            "^/(mcp|oauth|\\.well-known)": {
                target: "http://localhost:8601",
                changeOrigin: true,
            },
        },
    },
    preview: { port: 8600, strictPort: true },
    plugins: [solid({ ssr: true }), tailwindcss(), appSpaFallback()],
    resolve: {
        alias: {
            "@model": abs("./model"),
            "@engine": abs("./canvas/engine"),
            "@elements": abs("./canvas/elements"),
            "@themes": abs("./model/theme"),
            "@canvas": abs("./canvas"),
            "@ui": abs("./ui"),
            "@editor": abs("./editor"),
            "@app": abs("./app"),
            // no @services on purpose: a frontend import of services must fail the build
        },
    },
    build: {
        outDir: abs("./dist"),
        emptyOutDir: true,
        rollupOptions: {
            input: {
                website: abs("./index.html"),
                app: abs("./app/index.html"),
                publish: abs("./publish/index.html"),
                widget: abs("./widget/index.html"),
            },
        },
    },
});
