import type { ArtifactContent } from "@model/content";
import {
    badge,
    bgImage,
    bullets,
    button,
    callout,
    card,
    cell,
    chart,
    deck,
    diagram,
    group,
    img,
    quote,
    section,
    stat,
    t,
    table,
} from "@model/authoring";

export const galleo: ArtifactContent = deck(
    "couture",
    [
        // ── Cover ────────────────────────────────────────────────────────────
        section(
            "s1",
            "full",
            {
                a: cell(
                    group(
                        t("GALLEO", "label"),
                        t("Everyone can generate. We make it good.", "h1"),
                        t(
                            "Galleo is the taste-first content studio. Describe an idea once and it becomes a deck, a document, or a website — drafted in seconds, then polished into something you’d actually be proud to send.",
                            "subtitle",
                        ),
                        badge("SEED ROUND · 2026"),
                    ),
                ),
            },
            { background: bgImage("galleo-cover-studio", 0.55) },
        ),

        // ── 01 The problem ───────────────────────────────────────────────────
        section("s2", "split-6040", {
            a: cell(
                group(
                    t("01 — The problem", "label"),
                    t("AI made the first draft free. It also made the average one worse.", "h2"),
                    t(
                        "Generation collapsed the cost of a first draft to zero — and buried every audience under identical decks: the same five templates, the same stock photos, the same confident slop. The scarce thing was never words on a page. It was judgment — knowing what to cut, what to lead with, and how to make it land.",
                        "body",
                    ),
                ),
            ),
            b: cell(img("galleo-problem-desk", 0.82)),
        }),

        // ── The cost (stats) ─────────────────────────────────────────────────
        section("s3", "three-up", {
            a: cell(
                group(
                    t("THE COST", "label"),
                    stat(
                        "78%",
                        "of knowledge workers start with AI — and ship it nearly untouched",
                    ),
                ),
            ),
            b: cell(stat("1 in 6", "say the result is something they’re genuinely proud of")),
            c: cell(stat("9 hrs", "lost every week reformatting the same content across tools")),
        }),

        // ── Thesis ───────────────────────────────────────────────────────────
        section("s4", "full", {
            a: cell(
                quote(
                    "Speed turned everyone into a publisher overnight. Taste is the only moat left — and it’s the one thing a prompt can’t hand you.",
                    "— The Galleo thesis",
                ),
            ),
        }),

        // ── 02 The product ───────────────────────────────────────────────────
        section("s5", "split-4060", {
            a: cell(img("galleo-editor-canvas", 1.05)),
            b: cell(
                group(
                    t("02 — The product", "label"),
                    t("One canonical artifact. Every format is just a view.", "h2"),
                    t(
                        "Galleo holds your content as a single structured artifact — blocks, not slides. The same source renders as a full-screen deck, a scrollable document, or a published website, each composed by a real layout engine instead of a grid of templates.",
                        "body",
                    ),
                    bullets(
                        "Variable-height sections that reflow — not fixed slides",
                        "Themes designed by people, not generated by the thousand",
                        "An editor built for the 90% of the work that is refinement",
                    ),
                ),
            ),
        }),

        // ── One source, three formats ────────────────────────────────────────
        section("s6", "three-up", {
            a: cell(
                card(
                    img("galleo-format-deck", 1.4),
                    t("Deck", "h3"),
                    t(
                        "Present full-screen. Sections paginate into clean, on-brand slides.",
                        "caption",
                    ),
                ),
            ),
            b: cell(
                card(
                    img("galleo-format-doc", 1.4),
                    t("Document", "h3"),
                    t("The same blocks reflow into a readable, shareable document.", "caption"),
                ),
            ),
            c: cell(
                card(
                    img("galleo-format-site", 1.4),
                    t("Website", "h3"),
                    t("Publish a responsive, hosted page in a single click.", "caption"),
                ),
            ),
        }),

        // ── 03 How it works ──────────────────────────────────────────────────
        section("s7", "split-6040", {
            a: cell(
                group(
                    t("03 — How it works", "label"),
                    t("Draft in seconds. Then live in the editor.", "h2"),
                    t(
                        "Describe what you need and Galleo composes a real first draft — structured, on-theme, image-aware. Then the actual work begins: you refine, reorder, and sharpen until it’s yours. Switch formats whenever you like; the content travels with you.",
                        "body",
                    ),
                    diagram(
                        "process",
                        "Describe it, Galleo drafts, Refine with taste, Switch format, Publish",
                        180,
                    ),
                ),
            ),
            b: cell(img("galleo-howitworks-refine", 0.9)),
        }),

        // ── 04 The moat (feature background) ──────────────────────────────────
        section(
            "s8",
            "full",
            {
                a: cell(
                    group(
                        t("04 — The moat", "label"),
                        t("Generation is a commodity. Judgment isn’t.", "h2"),
                        t(
                            "Every rival is racing to produce the draft faster. We’re building the surface where the draft becomes good — an agent with real editorial taste, a layout engine that holds composition under pressure, and controls that reward the person who cares how it looks. Models get cheaper every quarter. Taste compounds.",
                            "body",
                        ),
                        button("See the editor in motion"),
                    ),
                ),
            },
            { background: bgImage("galleo-taste-studio", 0.6) },
        ),

        // ── 05 Why now ───────────────────────────────────────────────────────
        section("s9", "split-6040", {
            a: cell(
                group(
                    t("05 — Why now", "label"),
                    t("The first draft just became free — for everyone, all at once.", "h2"),
                    t(
                        "The tools people learned in 2010 were built for a world where making the draft was the hard part. That world is gone. Content volume has exploded since 2022, attention hasn’t grown an inch, and the premium has shifted decisively from output to polish. Whoever owns the finishing surface owns the category.",
                        "body",
                    ),
                ),
            ),
            b: cell(chart("bar", "8, 19, 38, 67, 110, 180", 240)),
        }),

        // ── 06 Market ────────────────────────────────────────────────────────
        section("s10", "three-up", {
            a: cell(
                group(
                    t("06 — Market", "label"),
                    stat("$48B", "spent on presentation + document software every year"),
                ),
            ),
            b: cell(stat("400M", "knowledge workers making content for a living")),
            c: cell(stat("12×", "more content created since 2022 — and climbing")),
        }),

        // ── 07 Traction ──────────────────────────────────────────────────────
        section("s11", "split-6040", {
            a: cell(
                group(
                    t("07 — Traction", "label"),
                    badge("NOW IN PAID BETA"),
                    t("Used hard by the teams we built it for.", "h2"),
                    t(
                        "Private alpha with 40 design-led teams. 1,200 artifacts created. 70% of activated users come back every week. Four months into the paid beta, the curve is steeper than we modeled.",
                        "body",
                    ),
                    callout(
                        "success",
                        t(
                            "Net revenue retention is 128% — teams that start with one seat keep pulling in the rest of the room.",
                            "body",
                        ),
                    ),
                ),
            ),
            b: cell(chart("line", "8, 14, 23, 38, 59, 92", 240)),
        }),

        // ── Customer love ────────────────────────────────────────────────────
        section("s12", "two-col", {
            a: cell(
                quote(
                    "We replaced three tools with Galleo and our decks stopped looking like everyone else’s. That’s the whole job.",
                    "Dana Whitfield · Head of Brand, Northwind",
                ),
            ),
            b: cell(
                quote(
                    "I sent the same story as a board deck and a press site in one afternoon. It used to take a week.",
                    "Marcus True · Founder, Cadence",
                ),
            ),
        }),

        // ── 08 Business model ────────────────────────────────────────────────
        section("s13", "full", {
            a: cell(
                group(
                    t("08 — Business model", "label"),
                    t("Bottom-up SaaS with a free tier that does real work.", "h2"),
                    table(
                        "Plan,Price,Built for,The hook\nFree,$0,Individuals,One published artifact + the full editor\nPro,$20/mo,Founders & freelancers,Unlimited artifacts + custom domains\nTeam,$36/seat,Design-led teams,Brand kits + shared library + roles\nEnterprise,Custom,Brand governance at scale,SSO + audit log + dedicated support",
                    ),
                    t(
                        "Land on Free, convert the individual on Pro, expand across the org on Team.",
                        "caption",
                    ),
                ),
            ),
        }),

        // ── 09 Why we win ────────────────────────────────────────────────────
        section("s14", "split-4060", {
            a: cell(img("galleo-compete-grid", 0.82)),
            b: cell(
                group(
                    t("09 — Why we win", "label"),
                    t("Generators race to the draft. We own the finish.", "h2"),
                    bullets(
                        "One source becomes deck, doc, and site — competitors pick one format and stop",
                        "A real layout engine, not a wall of slide templates",
                        "A taste-led agent, not a stock-photo firehose",
                        "We get stronger as models get cheaper — the value moves to our surface",
                    ),
                ),
            ),
        }),

        // ── 10 Go-to-market ──────────────────────────────────────────────────
        section("s15", "split-6040", {
            a: cell(
                group(
                    t("10 — Go-to-market", "label"),
                    t("Land with a designer. Expand to the org.", "h2"),
                    t(
                        "Galleo spreads the way the best tools do. One design-minded person makes something undeniably good, shares it, and the room asks how. Published artifacts are public by default — every page is a billboard. Self-serve converts the individual; brand kits and roles convert the team.",
                        "body",
                    ),
                ),
            ),
            b: cell(
                diagram(
                    "funnel",
                    "Designer discovers, Free artifact, Team adopts, Org standard",
                    220,
                ),
            ),
        }),

        // ── The team ─────────────────────────────────────────────────────────
        section("s16", "three-up", {
            a: cell(
                group(
                    img("galleo-team-mara", 1),
                    t("Mara Okafor", "h3"),
                    t("CEO · early Figma, led template systems", "caption"),
                ),
            ),
            b: cell(
                group(
                    img("galleo-team-theo", 1),
                    t("Theo Klein", "h3"),
                    t("CTO · ex-Linear, built the sync engine", "caption"),
                ),
            ),
            c: cell(
                group(
                    img("galleo-team-su", 1),
                    t("Su Lin", "h3"),
                    t("Head of Design · ex-Stripe brand", "caption"),
                ),
            ),
        }),

        // ── 11 Roadmap ───────────────────────────────────────────────────────
        section("s17", "full", {
            a: cell(
                group(
                    t("11 — Roadmap", "label"),
                    t("From editor to platform.", "h2"),
                    diagram(
                        "process",
                        "Taste-first editor, One-click publishing, Brand kits & teams, API & embeds",
                        180,
                    ),
                ),
            ),
        }),

        // ── 12 The ask ───────────────────────────────────────────────────────
        section("s18", "split-4060", {
            a: cell(
                group(
                    t("12 — The ask", "label"),
                    t("Raising a $4M seed to own the finishing surface.", "h2"),
                    t(
                        "Eighteen months of runway to reach 10,000 paying seats, ship the publishing platform, and make taste the default. We’re looking for partners who care how things look.",
                        "body",
                    ),
                    button("hello@galleo.app"),
                ),
            ),
            b: cell(
                group(
                    t("Use of funds", "h3"),
                    bullets(
                        "50% — Product & the taste-first editor",
                        "30% — Publishing & hosting platform",
                        "20% — Go-to-market & design partnerships",
                    ),
                ),
            ),
        }),

        // ── Vision close (feature background) ─────────────────────────────────
        section(
            "s19",
            "full",
            {
                a: cell(
                    group(
                        t("THE VISION", "label"),
                        t("A world where good is the default.", "h1"),
                        t(
                            "When the draft is free, the only thing worth paying for is judgment. Galleo is where it lives — the place your best ideas go to become something you’re proud to send.",
                            "subtitle",
                        ),
                        button("Let’s build it together"),
                    ),
                ),
            },
            { background: bgImage("galleo-vision-horizon", 0.55) },
        ),
    ],
    bgImage("galleo-bg", 0.34),
);
