import { existsSync, readFileSync } from "node:fs";
import { themeFontFamilies } from "@themes";

// Font-vendoring guard: fails when a family the product can render has no face to render it with.
//
// The stylesheet and the woff2 files are generated by `pnpm fonts:vendor` and committed, so nothing
// fetches a font at runtime. The failure this catches is quiet: a theme naming a family nobody
// vendored still renders, in whatever the browser falls back to, and looks merely wrong rather than
// broken. Exports are worse, because the face is embedded into the PDF.
//
// Self-verifying: a guard that can only report violations cannot tell you it has stopped working,
// so it asks for a family that cannot exist and fails if the check stays quiet.

const CSS = "public/fonts.css";
const out = (s: string): void => {
    process.stdout.write(`${s}\n`);
};

const familiesIn = (css: string): Set<string> =>
    new Set([...css.matchAll(/font-family:'([^']+)'/g)].map((m) => m[1]!));

const filesIn = (css: string): string[] =>
    [...css.matchAll(/url\('\/fonts\/([^']+)'\)/g)].map((m) => m[1]!);

function missing(css: string, wanted: string[]): string[] {
    const have = familiesIn(css);
    return wanted.filter((f) => !have.has(f));
}

if (!existsSync(CSS)) {
    out(`${CSS} is missing. Run: pnpm fonts:vendor`);
    process.exit(1);
}
const css = readFileSync(CSS, "utf8");

const gaps = missing(css, themeFontFamilies());
const orphans = filesIn(css).filter((f) => !existsSync(`public/fonts/${f}`));

// the self-check: a family nothing could have vendored must be reported
if (!missing(css, ["Galleo Nonexistent Face"]).length) {
    out("check:fonts is not reporting: a family with no vendored face passed");
    process.exit(1);
}

if (gaps.length || orphans.length) {
    for (const f of gaps) out(`  ${f}: named by a theme or the picker, but no face is vendored`);
    for (const f of orphans) out(`  ${f}: the stylesheet references a file that is not there`);
    out(`\nFAILED. Run: pnpm fonts:vendor`);
    process.exit(1);
}
out(`ok   ${familiesIn(css).size} families, ${filesIn(css).length} faces, all present`);
