import "dotenv/config";
import { writeFileSync } from "node:fs";
import { inArray } from "drizzle-orm";
import type { ArtifactContent } from "@model/artifact";
import { assetIdFromUrl } from "@model/media";
import { mapMediaRefs, mediaRefs } from "@model/artifact";
import { db } from "@services/db/client";
import { schema } from "@services/db/schema";
import { out } from "@services/utils/env";

/**
 * Regenerate website/showcase.ts from the demo library.
 *
 * The marketing page paints real artifacts through the real engine rather than showing captures of
 * them, so it needs their content in the bundle. It cannot read the corpus itself: the layering law
 * stops `website` at `@ui`, and the bodies live in services. This script sits in scripts/, which may
 * compose services and model, and writes the content down as a typed module the page can import.
 *
 * Pictures travel as the photograph's own url, not as `/api/media/asset/<uuid>`. Those uuids are
 * per-row, handed out by whichever database the demo library was seeded into, so a file generated
 * here referenced rows that exist on this machine and nowhere else: in production every one of them
 * 404s and the hero paints text on empty plates. Resolving each back to the `origin` it was adopted
 * from makes the module self-contained, which is what a marketing bundle has to be.
 *
 * Whole pieces travel, not covers. Trimming to the opening sections made every card look cut off:
 * a plate on a large monitor is tall enough to want ten sections, and it had three. The full twelve
 * are still about 170 KB, against roughly 3.6 MB for a wall of cover PNGs, so there is nothing to
 * save by cropping them.
 */

const PICKS: { title: string; format: "deck" | "doc" | "web" }[] = [
    { title: "Cinder · Bakery Wholesale", format: "deck" },
    { title: "The Bioscope · Centenary", format: "deck" },
    { title: "Ondine · Seed Round", format: "deck" },
    { title: "Maison Noor · Cendre", format: "deck" },
    { title: "Skálar · Fjord Residency", format: "doc" },
    { title: "Vespera · Violin Atelier", format: "doc" },
    { title: "The Long Table · Season Five", format: "doc" },
    { title: "Alpenglow Guides · Winter 2027", format: "doc" },
    { title: "The Palm House · Winter Garden", format: "web" },
    { title: "Hotel Solene", format: "web" },
    { title: "Norr · Island Knitwear", format: "web" },
    { title: "Blue Hour · Lisbon", format: "web" },
];

const HEAD = `import type { ArtifactContent } from "@model/artifact";

/**
 * The pieces the marketing page renders live.
 *
 * Content, not screenshots. The page paints these through the same engine the editor uses, which
 * costs a fraction of what a wall of PNGs costs to download, and lets the strips re-theme with the
 * rest of the page instead of being frozen in whatever theme they were captured in.
 *
 * Each is trimmed to its opening sections, because a strip cell is a cover rather than a document.
 * The \`theme\` on each piece is the one it was authored in; the page overrides it with the active
 * app theme at render time.
 *
 * Generated by scripts/showcase.ts. Do not edit by hand.
 */
export interface ShowcasePiece {
    title: string;
    format: "deck" | "doc" | "web";
    content: ArtifactContent;
}

export const SHOWCASE: ShowcasePiece[] = [
`;

/** id -> the url the asset was adopted from, for every canonical ref these pieces carry. */
async function originsFor(contents: ArtifactContent[]): Promise<Map<string, string>> {
    const ids = [
        ...new Set(
            contents
                .flatMap((c) => mediaRefs(c))
                .map(assetIdFromUrl)
                .filter((id): id is string => !!id),
        ),
    ];
    if (!ids.length) return new Map();
    const rows = await db
        .select({ id: schema.assets.id, origin: schema.assets.origin })
        .from(schema.assets)
        .where(inArray(schema.assets.id, ids));
    const found = new Map(rows.filter((r) => r.origin).map((r) => [r.id, r.origin!]));
    // an uploaded asset has bytes and no origin, so there is no url to ship and no silent fallback
    const stuck = ids.filter((id) => !found.has(id));
    if (stuck.length)
        throw new Error(`no origin url for ${stuck.length} assets: ${stuck.join(", ")}`);
    return found;
}

const deref = (content: unknown, origins: Map<string, string>): unknown =>
    mapMediaRefs(content, (url) => {
        const id = assetIdFromUrl(url);
        return (id && origins.get(id)) || url;
    });

async function main(): Promise<void> {
    const titles = PICKS.map((p) => p.title);
    const rows = await db
        .select({ title: schema.artifacts.title, content: schema.artifacts.draftContent })
        .from(schema.artifacts)
        .where(inArray(schema.artifacts.title, titles));
    const byTitle = new Map(rows.map((r) => [r.title, r.content as ArtifactContent]));

    const missing = PICKS.filter((p) => !byTitle.has(p.title)).map((p) => p.title);
    if (missing.length) throw new Error(`not in the library: ${missing.join(" | ")}`);

    const origins = await originsFor([...byTitle.values()]);

    const lines = PICKS.map((p) => {
        const full = deref(byTitle.get(p.title)!, origins) as ArtifactContent;
        const piece = {
            title: p.title,
            format: p.format,
            content: {
                format: p.format,
                theme: full.theme,
                sections: full.sections,
                ...(full.background ? { background: full.background } : {}),
            },
        };
        return `    ${JSON.stringify(piece)},`;
    });

    const src = `${HEAD}${lines.join("\n")}\n] as ShowcasePiece[];

export const showcaseFor = (format: ShowcasePiece["format"]): ShowcasePiece[] =>
    SHOWCASE.filter((p) => p.format === format);
`;
    writeFileSync(new URL("../website/showcase.ts", import.meta.url), src);
    const kb = Math.round(src.length / 1024);
    const sections = PICKS.reduce((n, p) => n + (byTitle.get(p.title)?.sections.length ?? 0), 0);
    out(`website/showcase.ts <- ${PICKS.length} pieces, ${sections} sections, ${kb} KB`);
    process.exit(0);
}

void main();
